strategy:
  matrix:
    ubuntu20_04:
      imageName: 'ubuntu-20.04'
    ubuntu18_04:
      imageName: 'ubuntu-18.04'
    ubuntu16_04:
      imageName: 'ubuntu-16.04'
    macos10_15:
      imageName: 'macos-10.15'
    macos10_14:
      imageName: 'macos-10.14'
    windows2016:
      imageName: 'vs2017-win2016'
    windows2019:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:

- script: |
    brew install libomp
  displayName: 'Install openmp (OSX)'
  condition: eq( variables['Agent.OS'], 'Darwin' )

- script: |
    mkdir cmake-build-debug
    cd cmake-build-debug
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DGENIE_USE_OPENMP=ON -DBUILD_DOCUMENTATION=ON
    ls -l
  displayName: 'Run CMake'

- script: |
    cd cmake-build-debug
    make --jobs
  displayName: 'Run Make'
  condition: ne( variables['Agent.OS'], 'Windows_NT' )

- task: VSBuild@1
  inputs:
    solution: 'cmake-build-debug\genie.sln'
    msbuildArgs: '-m' 
  displayName: 'Run MSVC'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- bash: |
    cp cmake-build-debug/bin/Debug/util-tests.exe cmake-build-debug/bin/util-tests
    cp cmake-build-debug/bin/Debug/gabac-app.exe cmake-build-debug/bin/gabac-app
  displayName: 'Copy MSVC files'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- bash: cmake-build-debug/bin/util-tests
  displayName: 'Run genie unit tests'

- bash: ci/gabac-roundtrip.sh
  displayName: 'Run GABAC Roundtrips'

