trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

#pool:
#  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir cmake-build-release
    cd cmake-build-release
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make --jobs
  displayName: 'Run CMake & Make'

