trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'

pool:
  vmImage: $(imageName)

steps:
- script: |
    mkdir cmake-build-release
    cd cmake-build-release
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make --jobs
  displayName: 'Run CMake & Make'

- script: |
    echo 'Run GABAC Roundtrips'
    ./ci/gabac-roundtrips.sh
  displayName: 'Run GABAC Roundtrips'

