trigger:
- master
- develop
- windows-test

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: |
    mkdir cmake-build-debug
    cd cmake-build-debug
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DGENIE_USE_OPENMP=ON -DBUILD_DOCUMENTATION=ON
    make --jobs
  displayName: 'Run CMake & Make'

- script: |
    echo 'Run genie unit tests'
    ./cmake-build-debug/bin/util-tests
  displayName: 'Run genie unit tests'

- script: |
    echo 'Run GABAC Roundtrips'
    ./ci/gabac-roundtrip.sh
  displayName: 'Run GABAC Roundtrips'

