trigger:
- master
- develop

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- script: |
    echo "$OSTYPE"
    mkdir cmake-build-debug
    cd cmake-build-debug
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DGENIE_USE_OPENMP=OFF -DBUILD_DOCUMENTATION=ON
    cmake --build ./
  displayName: 'Run CMake & Make'

- script: |
    echo 'Run genie unit tests'
    ./cmake-build-debug/bin/util-tests
  displayName: 'Run genie unit tests'

- script: |
    echo 'Run GABAC Roundtrips'
    chmod 777 ./ci/gabac-roundtrip.sh
    # ./ci/gabac-roundtrip.sh
  displayName: 'Run GABAC Roundtrips'

