stages:

- stage: 'Deployment'
  jobs:
  - job: 'Debian'
    strategy:
      matrix:
        ubuntu2204:
          imageName: 'ubuntu-22.04'
          artifactName: 'ubuntu2204'
          fileExt: ''
    pool:
      vmImage: $(imageName)
    steps:
    - bash: |
        ls -lah
    - checkout: none
    - download: current
      artifact: 'genie-release-$(artifactName)-$(Build.SourceVersion)'
      displayName: 'Download binaries'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'genie'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile'
        tags: |
          $(Build.SourceBranchName)
#  - job: 'OSX'
#    strategy:
 #     matrix:
 #       macos1200:
 #         imageName: 'macos-12'
 #         artifactName: 'macos1200'
 #         fileExt: ''
 #       macos1100:
 #         imageName: 'macos-11'
 #         artifactName: 'macos1100'
 #         fileExt: ''
 #   pool:
 #     vmImage: $(imageName)
 #   steps:
 #   - checkout: none
 #   - download: current
 #     artifact: 'genie-release-$(artifactName)-$(Build.SourceVersion)'
 #     displayName: 'Download binaries'
 #   - bash: echo "Not yet implemented"
 #     displayName: 'Build OSX dmg'
