trigger:
- master
- develop
- develop-windows-test

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- script: |
    echo "$OSTYPE"
    mkdir cmake-build-debug
    cd cmake-build-debug
    cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DGENIE_USE_OPENMP=OFF -DBUILD_DOCUMENTATION=ON -DBUILD_COVERAGE=ON
  displayName: 'Run CMake'

- script: |
    cd cmake-build-debug
    cmake --build ./ -- -j
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Build (Make)'

- script: |
    cd cmake-build-debug
    cmake --build ./
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Build (MSVC)'

- bash: |
    $(Build.SourcesDirectory)/cmake-build-debug/bin/util-tests
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Run genie unit tests (bash)'

- powershell: |
    $(Build.SourcesDirectory)\cmake-build-debug\bin\Debug\util-tests.exe
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Run genie unit tests (windows)'


