project("genie-test-annotation-parameter-set")
file(GLOB source_files "${CMAKE_CURRENT_SOURCE_DIR}/*.cc")
add_executable(${PROJECT_NAME} ${source_files})
target_link_libraries(${PROJECT_NAME} PRIVATE gtest_main genie-core genie-genotype-local genie-util)
add_test(NAME ${PROJECT_NAME} COMMAND ${PROJECT_NAME})
