function(print_summary)
    string(STRIP ${CMAKE_CXX_FLAGS} CMAKE_CXX_FLAGS)
    string(STRIP ${CMAKE_CXX_FLAGS_DEBUG} CMAKE_CXX_FLAGS_DEBUG)
    string(STRIP ${CMAKE_CXX_FLAGS_RELEASE} CMAKE_CXX_FLAGS_RELEASE)
    string(STRIP ${CMAKE_CXX_FLAGS_RELWITHDEBINFO} CMAKE_CXX_FLAGS_RELWITHDEBINFO)
    string(STRIP ${CMAKE_CXX_FLAGS_MINSIZEREL} CMAKE_CXX_FLAGS_MINSIZEREL)

    message(STATUS "")
    message(STATUS "******** Summary ********")
    message(STATUS "  System                 : ${CMAKE_SYSTEM_NAME}")
    message(STATUS "  CMake version          : ${CMAKE_VERSION}")
    message(STATUS "  CMake command          : ${CMAKE_COMMAND}")
    message(STATUS "  Build type             : ${CMAKE_BUILD_TYPE}")
    message(STATUS "  Build directory        : ${CMAKE_BINARY_DIR}")
    message(STATUS "  C++ compiler           : ${CMAKE_CXX_COMPILER}")
    message(STATUS "  C++ compiler ID        : ${CMAKE_CXX_COMPILER_ID}")
    message(STATUS "  C++ compiler version   : ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "  C++ standard version   : ${CMAKE_CXX_STANDARD}")
    message(STATUS "  CXX flags              : ${CMAKE_CXX_FLAGS}")
    if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        message(STATUS "  CXX flags <build type> : ${CMAKE_CXX_FLAGS_DEBUG}")
    elseif("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
        message(STATUS "  CXX flags <build type> : ${CMAKE_CXX_FLAGS_RELEASE}")
    elseif("${CMAKE_BUILD_TYPE}" STREQUAL "RelWithDebInfo")
        message(STATUS "  CXX flags <build type> : ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
    elseif("${CMAKE_BUILD_TYPE}" STREQUAL "MinSizeRel")
        message(STATUS "  CXX flags <build type> : ${CMAKE_CXX_FLAGS_MINSIZEREL}")
    else()
        message(WARNING "Build type not supported: ${CMAKE_BUILD_TYPE}")
    endif()
    message(STATUS "")
endfunction()
